services:
  init-kafka:
    image: 'bitnami/kafka:latest'
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --list

      echo -e 'Deleting kafka topics'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --topic create-auction-request --delete --if-exists
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --topic create-auction-response --delete --if-exists
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --topic bid-auction-request --delete --if-exists
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --topic bid-auction-response --delete --if-exists

      echo -e 'Creating kafka topics'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --create --if-not-exists --topic create-auction-request --replication-factor 3 --partitions 3
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --create --if-not-exists --topic create-auction-response --replication-factor 3 --partitions 3
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --create --if-not-exists --topic bid-auction-request --replication-factor 3 --partitions 3
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --create --if-not-exists --topic bid-auction-response --replication-factor 3 --partitions 3

      echo -e 'Successfully created the following topics:'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9192 --list
      "
    networks:
      - online-auction-network

networks:
  online-auction-network:
    driver: bridge
